version: '3'
services:
  jenkins:
    image: bitnami/jenkins:latest
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - JENKINS_PASSWORD=admin
      - JENKINS_USER=admin
    volumes:
      - jenkins_data:/bitnami

volumes:
  jenkins_data:
    driver: local

